
from firedrake import IntervalMesh, PeriodicIntervalMesh, RectangleMesh, PeriodicRectangleMesh, BoxMesh, PeriodicBoxMesh, Mesh, FacetNormal
from firedrake import FunctionSpace, VectorFunctionSpace, dx, ds, dS, ExtrudedMesh
import finat
import FIAT

def gauss_lobatto_legendre_cube_rule(dimension, degree):
    make_tensor_rule = finat.quadrature.TensorProductQuadratureRule
    result = gauss_lobatto_legendre_line_rule(degree)
    for _ in range(1, dimension):
        line_rule = gauss_lobatto_legendre_line_rule(degree)
        result = make_tensor_rule([result, line_rule])
    return result

def gauss_lobatto_legendre_line_rule(degree):
    fiat_make_rule = FIAT.quadrature.GaussLobattoLegendreQuadratureLineRule
    fiat_rule = fiat_make_rule(FIAT.ufc_simplex(1), degree + 1)
    finat_ps = finat.point_set.GaussLobattoLegendrePointSet
    finat_qr = finat.quadrature.QuadratureRule
    return finat_qr(finat_ps(fiat_rule.get_points()), fiat_rule.get_weights())

def set_dimension(parameters):
    if parameters['mesh']['type'] in ['line', 'line-periodic']:
        parameters['mesh']['dim'] = 1
    elif parameters['mesh']['type'] in ['rectangle', 'rectangle-periodic']:
        parameters['mesh']['dim'] = 2
    elif parameters['mesh']['type'] in ['box', 'box-periodic']:
        parameters['mesh']['dim'] = 3
    elif parameters['mesh']['type'] == 'file':
        parameters['mesh']['dim'] = XXX #NEED TO READ SOMEHOW

def mesh_size(msh):
    DG0 = FunctionSpace(msh, "DG", 0)
    h = Function(DG0).interpolate(CellDiameter(msh))
    with h.dat.vec as hvec:
        _, maxh = hvec.max()
    return maxh


def get_mesh_and_spaces(parameters, initcond):

#HONESTLY MAYBE WE JUST SCALE + RECENTER ALL THE MESHES?
#at least all the autogenerated ones..
    if parameters['mesh']['type'] == 'line':
        left =  initcond.xc -initcond.Lx/2.
        right = initcond.xc + initcond.Lx/2.
        mesh = IntervalMesh(parameters['mesh']['nx'], left, right)
    elif parameters['mesh']['type'] == 'line-periodic':
        mesh = PeriodicIntervalMesh(parameters['mesh']['nx'], initcond.Lx)
#NEED TO SCALE+CENTER MESH COORDINATES
    elif parameters['mesh']['type'] == 'rectangle':
        left_x =  initcond.xc - initcond.Lx/2.
        right_x = initcond.xc + initcond.Lx/2.
        left_y =  initcond.yc - initcond.Ly/2.
        right_y = initcond.yc + initcond.Ly/2.
        mesh = RectangleMesh(parameters['mesh']['nx'], parameters['mesh']['ny'], right_x, right_y, originX=left_x, originY=left_y, quadrilateral=not parameters['mesh']['simplicial_cells'], diagonal=parameters['mesh']['diagonal'])
    elif parameters['mesh']['type'] == 'rectangle-periodic':
        mesh = PeriodicRectangleMesh(parameters['mesh']['nx'], parameters['mesh']['ny'], initcond.Lx, initcond.Ly, quadrilateral=not parameters['mesh']['simplicial_cells'], diagonal=parameters['mesh']['diagonal'])
        mesh.dx = initcond.Lx / parameters['mesh']['nx']
        mesh.dy = initcond.Ly / parameters['mesh']['ny']
#NEED TO SCALE+CENTER MESH COORDINATES
    elif parameters['mesh']['type'] == 'box':
#THIS WILL CHOKE IF DOING HEXAHEDRAL CELLS
        mesh = BoxMesh(parameters['mesh']['nx'], parameters['mesh']['ny'], parameters['mesh']['nz'], initcond.Lx, initcond.Ly, initcond.Lz, hexahedral=not parameters['mesh']['simplicial_cells'], diagonal=parameters['mesh']['diagonal'])
#NEED TO SCALE+CENTER MESH COORDINATES
    elif parameters['mesh']['type'] == 'box-periodic':
#H(div) and H(curl) for hexehedra are only supported on extruded meshes for now'
        if parameters['mesh']['simplicial_cells']:
            mesh = PeriodicBoxMesh(parameters['mesh']['nx'], parameters['mesh']['ny'], parameters['mesh']['nz'], initcond.Lx, initcond.Ly, initcond.Lz, hexahedral=False)
        else:
            mesh2D = PeriodicRectangleMesh(parameters['mesh']['nx'], parameters['mesh']['ny'], initcond.Lx, initcond.Ly, quadrilateral=True)
            mesh = ExtrudedMesh(mesh2D, parameters['mesh']['nz'], layer_height=initcond.Lz / parameters['mesh']['nz'], extrusion_type='uniform', periodic=True)
            mesh.dx = initcond.Lx / parameters['mesh']['nx']
            mesh.dy = initcond.Ly / parameters['mesh']['ny']
            mesh.dz = initcond.Lz / parameters['mesh']['nz']
    elif parameters['mesh']['type'] == 'file':
        mesh = Mesh(parameters['mesh']['meshfile'])
        if parameters['mesh']['scale_center_meshfile_coords']:
#ADD THIS
            pass
#POSSIBLY NEED TO SCALE+CENTER MESH COORDINATES
    else:
        raise ValueError("mesh " + parameters['mesh']['type'] + " is unknown")
    set_dimension(parameters)
    spaces = DeRhamComplex(mesh, parameters)
    return [mesh, spaces]

#LOTS OF CHOICES HERE- QUADS VS TRIANGLES, DIFFERENT FAMILIES, ETC.

class DeRhamComplex():

    def __init__(self, mesh, parameters):

        self.n = FacetNormal(mesh)
        self.order = parameters['spatial-discretization']['order']
        self.family = parameters['spatial-discretization']['family']
        self.mesh = mesh
        if parameters['spatial-discretization']['family'] == 'Q':
            self.CG = FunctionSpace(mesh, 'CG', parameters['spatial-discretization']['order'], variant="spectral") #TRY Q??
            self.DG = FunctionSpace(mesh, 'DG', parameters['spatial-discretization']['order']-1, variant="spectral") #TRY DQ?
#PLOTTING FOR DG L2 IS BROKEN
#UNCLEAR IF WE REALLY NEED DG L2?
            if mesh.cell_dimension() == 1:
                self.DGV = self.DG
                self.Hdiv = self.CG
                self.Hcurl = None
                self.CGV = self.CG
            if mesh.cell_dimension() == 2:
                self.DGV = VectorFunctionSpace(mesh, 'DG', parameters['spatial-discretization']['order']-1) #TRY DQ?
                self.CGV = VectorFunctionSpace(mesh, 'CG', parameters['spatial-discretization']['order']) #TRY Q?
                self.Hdiv = FunctionSpace(mesh, 'RTCF', parameters['spatial-discretization']['order'])
                self.Hcurl = FunctionSpace(mesh, 'RTCE', parameters['spatial-discretization']['order'])
#THIS IS NEEDED SINCE 3D HEXAHEDRA ARE NOT SUPPORTED YET
            if mesh.cell_dimension() == (2,1):
                self.DGV = VectorFunctionSpace(mesh, 'DG', parameters['spatial-discretization']['order']-1) #TRY DQ?
                self.CGV = VectorFunctionSpace(mesh, 'CG', parameters['spatial-discretization']['order']) #TRY DQ?
                self.Hdiv = FunctionSpace(mesh, 'NCF', parameters['spatial-discretization']['order'])
                self.Hcurl = FunctionSpace(mesh, 'NCE', parameters['spatial-discretization']['order'])
            if parameters['spatial-discretization']['lump_mass']:
                gll_rule = gauss_lobatto_legendre_cube_rule(dimension=parameters['mesh']['dim'], degree=self.CG.ufl_element().degree())
                gll_surf_rule = gauss_lobatto_legendre_cube_rule(dimension=parameters['mesh']['dim']-1, degree=self.CG.ufl_element().degree())
                self.dx = dx(scheme=gll_rule)
                self.dS = dS(scheme=gll_surf_rule)
                self.ds = ds(scheme=gll_surf_rule)
            else:
                self.dx = dx
                self.dS = dS
                self.ds = ds

        #elif parameters['family'] == 'P-':
        #    pass
        #elif parameters['family'] == 'P+':
        #    pass
        else:
            raise ValueError("FEEC family " + parameters['spatial-discretization']['family'] + " is unknown")
