
from firedrake import IntervalMesh, PeriodicIntervalMesh, RectangleMesh, PeriodicRectangleMesh, BoxMesh, PeriodicBoxMesh, Mesh, FacetNormal
from firedrake import FunctionSpace, VectorFunctionSpace, dx, ds, dS
import finat
import FIAT

def gauss_lobatto_legendre_cube_rule(dimension, degree):
    make_tensor_rule = finat.quadrature.TensorProductQuadratureRule
    result = gauss_lobatto_legendre_line_rule(degree)
    for _ in range(1, dimension):
        line_rule = gauss_lobatto_legendre_line_rule(degree)
        result = make_tensor_rule([result, line_rule])
    return result

def gauss_lobatto_legendre_line_rule(degree):
    fiat_make_rule = FIAT.quadrature.GaussLobattoLegendreQuadratureLineRule
    fiat_rule = fiat_make_rule(FIAT.ufc_simplex(1), degree + 1)
    finat_ps = finat.point_set.GaussLobattoLegendrePointSet
    finat_qr = finat.quadrature.QuadratureRule
    return finat_qr(finat_ps(fiat_rule.get_points()), fiat_rule.get_weights())

def set_dimension(parameters):
    if parameters['mesh'] in ['line', 'line-periodic']:
        parameters['dim'] = 1
    elif parameters['mesh'] in ['rectangle', 'rectangle-periodic']:
        parameters['dim'] = 2
    elif parameters['mesh'] in ['box', 'box-periodic']:
        parameters['dim'] = 3
    elif parameters['mesh'] == 'file':
        parameters['dim'] = XXX #NEED TO READ SOMEHOW



def get_mesh_and_spaces(parameters, initcond):

#HONESTLY MAYBE WE JUST SCALE + RECENTER ALL THE MESHES?
#at least all the autogenerated ones..
    if parameters['mesh'] == 'line':
        left =  initcond.xc -initcond.Lx/2.
        right = initcond.xc + initcond.Lx/2.
        mesh = IntervalMesh(parameters['nx'], left, right)
    elif parameters['mesh'] == 'line-periodic':
        mesh = PeriodicIntervalMesh(parameters['nx'], initcond.Lx)
#NEED TO SCALE+CENTER MESH COORDINATES
    elif parameters['mesh'] == 'rectangle':
        left_x =  initcond.xc - initcond.Lx/2.
        right_x = initcond.xc + initcond.Lx/2.
        left_y =  initcond.yc - initcond.Ly/2.
        right_y = initcond.yc + initcond.Ly/2.
        mesh = RectangleMesh(parameters['nx'], parameters['ny'], right_x, right_y, originX=left_x, originY=left_y, quadrilateral=not parameters['simplicial_cells'], diagonal=parameters['diagonal'])
    elif parameters['mesh'] == 'rectangle-periodic':
        mesh = PeriodicRectangleMesh(parameters['nx'], parameters['ny'], initcond.Lx, initcond.Ly, quadrilateral=not parameters['simplicial_cells'], diagonal=parameters['diagonal'])
        mesh.dx = initcond.Lx / parameters['nx']
        mesh.dy = initcond.Ly / parameters['ny']
#NEED TO SCALE+CENTER MESH COORDINATES
    elif parameters['mesh'] == 'box':
        mesh = BoxMesh(parameters['nx'], parameters['ny'], parameters['nz'], initcond.Lx, initcond.Ly, initcond.Lz, hexahedral=not parameters['simplicial_cells'], diagonal=parameters['diagonal'])
#NEED TO SCALE+CENTER MESH COORDINATES
    elif parameters['mesh'] == 'box-periodic':
        mesh = PeriodicBoxMesh(parameters['nx'], parameters['ny'], parameters['nz'], initcond.Lx, initcond.Ly, initcond.Lz, hexahedral=not parameters['simplicial_cells'])
        mesh.dx = initcond.Lx / parameters['nx']
        mesh.dy = initcond.Ly / parameters['ny']
        mesh.dz = initcond.Lz / parameters['nz']
#NEED TO SCALE+CENTER MESH COORDINATES
    elif parameters['mesh'] == 'file':
        mesh = Mesh(parameters['meshfile'])
        if parameters['scale_center_meshfile_coords']:
#ADD THIS
            pass
#POSSIBLY NEED TO SCALE+CENTER MESH COORDINATES
    else:
        raise ValueError("mesh " + parameters['mesh'] + " is unknown")
    set_dimension(parameters)
    spaces = DeRhamComplex(mesh, parameters)
    return [mesh, spaces]

#LOTS OF CHOICES HERE- QUADS VS TRIANGLES, DIFFERENT FAMILIES, ETC.

class DeRhamComplex():

    def __init__(self, mesh, parameters):

        self.n = FacetNormal(mesh)
        self.order = parameters['order']
        self.family = parameters['family']
        self.mesh = mesh

        if parameters['family'] == 'Q':
            self.CG = FunctionSpace(mesh, 'CG', parameters['order'], variant="spectral") #TRY Q??
            self.DG = FunctionSpace(mesh, 'DG', parameters['order']-1, variant="spectral") #TRY DQ?
#PLOTTING FOR DG L2 IS BROKEN
#UNCLEAR IF WE REALLY NEED DG L2?
            if mesh.cell_dimension() == 1:
                self.DGV = self.DG
                self.Hdiv = self.CG
                self.Hcurl = None
                self.CGV = self.CG
            if mesh.cell_dimension() == 2:
                self.DGV = VectorFunctionSpace(mesh, 'DG', parameters['order']-1) #TRY DQ?
                self.CGV = VectorFunctionSpace(mesh, 'CG', parameters['order']) #TRY Q?
                self.Hdiv = FunctionSpace(mesh, 'RTCF', parameters['order'])
                self.Hcurl = FunctionSpace(mesh, 'RTCE', parameters['order'])
            if mesh.cell_dimension() == 3:
                self.DGV = VectorFunctionSpace(mesh, 'DG', parameters['order']-1) #TRY DQ?
                self.CGV = VectorFunctionSpace(mesh, 'CG', parameters['order']) #TRY DQ?
                self.Hdiv = VectorFunctionSpace(mesh, 'CG', parameters['order'])
                self.Hcurl = VectorFunctionSpace(mesh, 'CG', parameters['order'])
#THESE ARE NOT CURRENTLY SUPPORTED, UNFORTUNATELY
                #self.Hdiv = FunctionSpace(mesh, 'NCF', parameters['order'])
                #self.Hcurl = FunctionSpace(mesh, 'NCE', parameters['order'])

            if parameters['lump_mass']:
                gll_rule = gauss_lobatto_legendre_cube_rule(dimension=parameters['dim'], degree=self.CG.ufl_element().degree())
                gll_surf_rule = gauss_lobatto_legendre_cube_rule(dimension=parameters['dim']-1, degree=self.CG.ufl_element().degree())
                self.dx = dx(scheme=gll_rule)
                self.dS = dS(scheme=gll_surf_rule)
                self.ds = ds(scheme=gll_surf_rule)
            else:
                self.dx = dx
                self.dS = dS
                self.ds = ds

        #elif parameters['family'] == 'P-':
        #    pass
        #elif parameters['family'] == 'P+':
        #    pass
        else:
            raise ValueError("FEEC family " + parameters['family'] + " is unknown")
