name: Auto test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'
      - 'scripts/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'
      - 'scripts/**'
  
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    container:
      image: firedrakeproject/firedrake:latest
      options: --user root
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install pytest
      run: |
        pip install pytest yaml

    - name: Run pytest
      env:
          PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest -v -s
